### ISSUE TITLE
Can't Use Embedded ZIP File

### ISSUE THREAD

**Issue by eXpl0it3r** [b3b00/sharpfilesystem#4]
Switching from SharpZipLib to ZipArchive made it a requirement for NetZipArchiveFileSystem that the Stream is not only readable (and seekable), but also writeable, which doesn't work when you take the stream of a read-only embedded resource file.

Would there be a possibility to add support to read-only ZIP files as well?

I'd guess that having an additional function `OpenReadOnly(Stream s)` which then opens the file with `ZipArchiveMode.Read` should be enough. Maybe add an additional check to the write methods to throw an exception in ReadOnly mode.

**Comment by b3b00** [comment]
@eXpl0it3r I'm quite busy these days. Could you try your solution and propose a pull request ? I will be happy to merge it, if you succeed. Don't forget a minimal unit test.

**Comment by b3b00** [comment]
@eXpl0it3r I've just published a new nuget version (1.0.7) with your PR. I let you close this issue

**Comment by eXpl0it3r** [comment]
Oh awesome, that was quick, thanks a lot! 🙂
I'd be happy to add some tests as well, but first wanted to enable CI for PRs as well, which I just PR-ed with #6

I'll write a test and check that the implementation fully works, afterwards close the issue.

**Comment by b3b00** [comment]
thanks for you PR #6 , I've just merge it.

**Comment by eXpl0it3r** [comment]
Thanks again for your quick response! 🙂 

As mentioned in #7, you may want to publish a new NuGet package, since I broke the standard NetZipArchiveFileSystem, as it will throw when trying to open an entry as ReadWrite, but I'll close this issue.
